version: '3.8'

services:
  # --------------------------------------------------------------------------------------------------------------------
  # Service: BITPING
  # Site: https://bitping.com
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_bitping:
    container_name: cash-mint_bitping
    image: bitping/bitpingd:latest
    restart: always
    environment:
      - TZ=${CFG_TIMEZONE}
    volumes:
      - ${CFG_WORKING_DIRECTORY}/.appdata/bitping:/root/.bitpingd
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    entrypoint: /bin/bash -c "chmod +x /app/bitpingd && /app/bitpingd login --email '${BITPING_EMAIL}' --password '${BITPING_PASSWORD}' && sleep 5 && /app/bitpingd run"
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.100

  # --------------------------------------------------------------------------------------------------------------------
  # Service: EARNFM
  # Site: https://earn.fm/ref/BEARFZQR (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_earnfm:
    container_name: cash-mint_earnfm
    image: earnfm/earnfm-client:latest
    restart: always
    environment:
      - EARNFM_TOKEN=${EARNFM_TOKEN}
      - TZ=${CFG_TIMEZONE}
    volumes:
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.101

  # --------------------------------------------------------------------------------------------------------------------
  # Service: HONEYGAIN
  # Site: https://r.honeygain.me/HARYO1972B (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_honeygain:
    container_name: cash-mint_honeygain
    image: honeygain/honeygain:latest
    restart: always
    environment:
      - TZ=${CFG_TIMEZONE}
    volumes:
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    command: -tou-accept -email ${HONEYGAIN_EMAIL} -pass ${HONEYGAIN_PASSWORD} -device ${HONEYGAIN_DEVICE}
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.102

  # --------------------------------------------------------------------------------------------------------------------
  # Service: MYSTERIUM
  # Site: https://mystnodes.com
  # Local Dashboard: http://localhost:<MYSTERIUM_DASHBOARD_PORT>
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_mysterium:
    container_name: cash-mint_mysterium
    image: mysteriumnetwork/myst:latest
    restart: always
    environment:
      - TZ=${CFG_TIMEZONE}
    volumes:
      - ${CFG_WORKING_DIRECTORY}/.appdata/mysterium:/var/lib/mysterium-node
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    cap_add:
      - NET_ADMIN
    ports:
      - "${MYSTERIUM_DASHBOARD_PORT}:4449"
    command: service --agreed-terms-and-conditions
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.103

  # --------------------------------------------------------------------------------------------------------------------
  # Service: PACKETSTREAM
  # Site: https://packetstream.io/?psr=1RV8 (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_packetstream:
    container_name: cash-mint_packetstream
    image: packetstream/psclient:latest
    restart: always
    environment:
      - CID=${PACKETSTREAM_CID}
      - TZ=${CFG_TIMEZONE}
    volumes:
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.104

  # --------------------------------------------------------------------------------------------------------------------
  # Service: PAWNS
  # Site: https://pawns.app/?r=3284830 (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_pawns:
    container_name: cash-mint_pawns
    image: iproyal/pawns-cli:latest
    restart: always
    environment:
      - TZ=${CFG_TIMEZONE}
    volumes:
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    command: -email=${PAWNS_EMAIL} -password=${PAWNS_PASSWORD} -device-name=${PAWNS_DEVICE_NAME} -device-id=${PAWNS_DEVICE_ID} -accept-tos
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.105

  # --------------------------------------------------------------------------------------------------------------------
  # Service: PROXYLITE
  # Site: https://proxylite.ru/?r=8Q4XCYWF (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_proxylite:
    container_name: cash-mint_proxylite
    image: proxylite/proxyservice:latest
    restart: always
    environment:
      - USER_ID=${PROXYLITE_USER_ID}
      - TZ=${CFG_TIMEZONE}
    volumes:
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.106

  # --------------------------------------------------------------------------------------------------------------------
  # Service: PROXYRACK
  # Site: https://peer.proxyrack.com/ref/phzcnf5r7nq1idtx4rhgglt6ayrtvqgkb8nwhkic (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_proxyrack:
    container_name: cash-mint_proxyrack
    image: proxyrack/pop:latest
    restart: always
    environment:
      - UUID=${PROXYRACK_UUID}
      - TZ=${CFG_TIMEZONE}
    volumes:
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.107

  # --------------------------------------------------------------------------------------------------------------------
  # Service: REPOCKET
  # Site: https://link.repocket.co/WqgJ (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_repocket:
    container_name: cash-mint_repocket
    image: repocket/repocket:latest
    restart: always
    environment:
      - RP_EMAIL=${REPOCKET_RP_EMAIL}
      - RP_API_KEY=${REPOCKET_RP_API_KEY}
      - TZ=${CFG_TIMEZONE}
    volumes:
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.108

  # --------------------------------------------------------------------------------------------------------------------
  # Service: WATCHTOWER
  # Site: https://github.com/containrrr/watchtower
  # Notes: Watchtower can update the running version of your containerized app. This tool is OP :D
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_watchtower:
    container_name: cash-mint_watchtower
    image: containrrr/watchtower:latest
    restart: always
    environment:
      - TZ=${CFG_TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:${CFG_TIMEZONE_FILE}:ro
    command: >
      --cleanup
      --log-level trace
      --include-restarting
      --include-stopped
      --interval 1800
      cash-mint_bitping
      cash-mint_earnfm
      cash-mint_honeygain
      cash-mint_mysterium
      cash-mint_packetstream
      cash-mint_pawns
      cash-mint_proxylite
      cash-mint_proxyrack
      cash-mint_repocket
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.109

# ----------------------------------------------------------------------------------------------------------------------
# If you know what to do, this option may help in implement a more secure architecture by isolating
# different components of the application.
# ----------------------------------------------------------------------------------------------------------------------
networks:
  cash-mint_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.88.0/24
# ----------------------------------------------------------------------------------------------------------------------
