version: '3.8'

services:
  # --------------------------------------------------------------------------------------------------------------------
  # Service: BITPING
  # Site: https://bitping.com
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_bitping:
    container_name: cash-mint_bitping
    image: bitping/bitpingd:latest
    restart: always
    volumes:
      - ${CFG_WORKING_DIRECTORY}/.appdata/bitping:/root/.bitpingd
    entrypoint: >
      /bin/bash -c "
      /app/bitpingd login
      --email '${BITPING_EMAIL}'
      --password '${BITPING_PASSWORD}' &&
      /app/docker.sh"
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.2

  # --------------------------------------------------------------------------------------------------------------------
  # Service: EARNFM
  # Site: https://earn.fm/ref/BEARFZQR (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_earnfm:
    container_name: cash-mint_earnfm
    image: earnfm/earnfm-client:latest
    restart: always
    environment:
      - EARNFM_TOKEN=${EARNFM_TOKEN}
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.3

  # --------------------------------------------------------------------------------------------------------------------
  # Service: HONEYGAIN
  # Site: https://r.honeygain.me/HARYO1972B (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_honeygain:
    container_name: cash-mint_honeygain
    image: honeygain/honeygain:latest
    restart: always
    command: >
      -email ${HONEYGAIN_EMAIL} 
      -pass ${HONEYGAIN_PASSWORD} 
      -device ${HONEYGAIN_DEVICE}
      -tou-accept
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.4

  # --------------------------------------------------------------------------------------------------------------------
  # Service: MYSTERIUM
  # Site: https://mystnodes.co/?referral_code=qGKgwIJSEpxvOKhZUb1BDsa1xSdPCLjTAWaacX25 (referral)
  # Local Dashboard: http://localhost:<MYSTERIUM_DASHBOARD_PORT>
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_mysterium:
    container_name: cash-mint_mysterium
    image: mysteriumnetwork/myst:latest
    restart: always
    volumes:
      - ${CFG_WORKING_DIRECTORY}/.appdata/mysterium:/var/lib/mysterium-node
    cap_add:
      - NET_ADMIN
    ports:
      - "${MYSTERIUM_DASHBOARD_PORT}:4449"
    command: >
      service 
      --agreed-terms-and-conditions
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.5

  # --------------------------------------------------------------------------------------------------------------------
  # Service: PACKETSTREAM
  # Site: https://packetstream.io/?psr=1RV8 (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_packetstream:
    container_name: cash-mint_packetstream
    image: packetstream/psclient:latest
    restart: always
    environment:
      - CID=${PACKETSTREAM_CID}
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.6

  # --------------------------------------------------------------------------------------------------------------------
  # Service: PAWNS
  # Site: https://pawns.app/?r=3284830 (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_pawns:
    container_name: cash-mint_pawns
    image: iproyal/pawns-cli:latest
    restart: always
    command: >
      -email=${PAWNS_EMAIL} 
      -password=${PAWNS_PASSWORD} 
      -device-name=${PAWNS_DEVICE_NAME} 
      -device-id=${PAWNS_DEVICE_ID} 
      -accept-tos
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.7

  # --------------------------------------------------------------------------------------------------------------------
  # Service: PROXYLITE
  # Site: https://proxylite.ru/?r=8Q4XCYWF (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_proxylite:
    container_name: cash-mint_proxylite
    image: proxylite/proxyservice:latest
    restart: always
    environment:
      - USER_ID=${PROXYLITE_USER_ID}
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.8

  # --------------------------------------------------------------------------------------------------------------------
  # Service: PROXYRACK
  # Site: https://peer.proxyrack.com/ref/phzcnf5r7nq1idtx4rhgglt6ayrtvqgkb8nwhkic (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_proxyrack:
    container_name: cash-mint_proxyrack
    image: proxyrack/pop:latest
    restart: always
    environment:
      - UUID=${PROXYRACK_UUID}
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.9

  # --------------------------------------------------------------------------------------------------------------------
  # Service: REPOCKET
  # Site: https://link.repocket.co/WqgJ (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_repocket:
    container_name: cash-mint_repocket
    image: repocket/repocket:latest
    restart: always
    environment:
      - RP_EMAIL=${REPOCKET_RP_EMAIL}
      - RP_API_KEY=${REPOCKET_RP_API_KEY}
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.10

  # --------------------------------------------------------------------------------------------------------------------
  # Service: TRAFFMONETIZER
  # Site: https://traffmonetizer.com/?aff=1612556 (referral)
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint_traffmonetizer:
    container_name: cash-mint_traffmonetizer
    image: traffmonetizer/cli_v2:latest
    restart: always
    command: >
      start 
      accept 
      --token ${TRAFFMONETIZER_TOKEN}
      --device-name ${TRAFFMONETIZER_DEVICE_NAME}
      status
    networks:
      cash-mint_network:
        ipv4_address: 172.16.88.11

  # --------------------------------------------------------------------------------------------------------------------
  # Service Util: WATCHTOWER
  # Site: https://github.com/containrrr/watchtower
  # Usage: Watchtower will update the cash-mint containers version and
  #        will restart it with the same commands as the first-run.
  # --------------------------------------------------------------------------------------------------------------------
  cash-mint-util_watchtower:
    container_name: cash-mint-util_watchtower
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --cleanup
      --log-level trace
      --include-restarting
      --include-stopped
      --interval ${CFG_CONTAINER_UPDATE_INTERVAL_SEC}
      cash-mint_bitping
      cash-mint_earnfm
      cash-mint_honeygain
      cash-mint_mysterium
      cash-mint_packetstream
      cash-mint_pawns
      cash-mint_proxylite
      cash-mint_proxyrack
      cash-mint_repocket
      cash-mint_traffmonetizer
    networks:
      cash-mint-util_network:
        ipv4_address: 172.16.89.2

# ----------------------------------------------------------------------------------------------------------------------
# If you know what to do, this option may help in implement a more secure architecture by isolating
# different components of the application.
# ----------------------------------------------------------------------------------------------------------------------
networks:
  # network for cash-mint_* containers
  cash-mint_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.88.0/24

  # network for cash-mint-util_* containers
  cash-mint-util_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.89.0/24
